# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Test and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Test and build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses :  actions/upload-artifact@v2
      with:
        name: JAR file
        path: ./target/core-*.jar
